blank_issues_enabled: false
contact_links:
  - name: Kookaburra Docs.
    url: https://azproductions.github.io/Kookaburra/
    about: The official Kookaburra docs.
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
